server:
  port: ${PORT:0}
  servlet:
    contextPath: /client

spring:
  application:
    name: client
  #security:
  #  user:
  #    name: nitesh
  #    password: nitesh

eurekaserver:
  name: eureka

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

eureka:
  #instance:
  #  hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8900/eurekaserver/${eurekaserver.name}/
    healthcheck:
      enabled: true
    should-unregister-on-shutdown: false

  instance:
    lease-renewal-interval-in-seconds: 60
  #  preferIpAddress: true
  #  ipAddress: 10.240.66.224
    #instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  #  name: localhost
    homePageUrlPath: ${server.servlet.contextPath}/
    statusPageUrlPath: ${server.servlet.contextPath}/actuator/health
    healthCheckUrlPath: ${server.servlet.contextPath}/actuator/health





